### PR TITLE
Feat/handle scroll

### PR DESCRIPTION
**Pull request by pvlv**
PR based on - https://github.com/theKashey/React-stroller/pull/4

### CODE REVIEW

**Comment by theKashey** [comment]
So what problem `onScroll` solves? Why you might need it?
Can [StrollerState](https://github.com/theKashey/React-stroller#scrollindicators) help here?

**Comment by pvlv** [comment]
> So what problem `onScroll` solves? Why you might need it?
> Can [StrollerState](https://github.com/theKashey/React-stroller#scrollindicators) help here?

For use with react-window - https://codesandbox.io/s/vmr1l0p463?file=/index.js (example react-custom-scrollbar with react-window)

react-window - listen "scroll" event and dynamically displays elements.

**Comment by theKashey** [comment]
👍

**Comment by theKashey** [comment]
v1.8.0 has been published

**Pull request merged**
